#!/bin/sh

# Verify if file is readable and run it
[ -r /etc/lsb-release ] && . /etc/lsb-release

# If $DISTRIB_DESCRIPTION is empty and /usr/bin/lsb_release is executable
if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
	# Fall back to using the very slow lsb_release utility
	DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

printf "Welcome to %s (%s %s %s)\n" "$DISTRIB_DESCRIPTION" "$(uname -o)" "$(uname -r)" "$(uname -m)"
