#!/bin/bash

echo ""
echo "***********************************************"
echo "*                                             *"
echo "*   Access forbidden to unauthorized users.   *"
echo "*                                             *"
echo "***********************************************"
echo ""
